; sensor-beacon — MeshCore out-of-tree beacon firmware

[platformio]
extra_configs =
  platformio.local.ini

[arduino_base]
framework = arduino
monitor_speed = 115200
extra_scripts = pre:pre_build.py
lib_deps =
  MeshCore=https://github.com/meshcore-dev/MeshCore.git#v1.16.0
  adafruit/Adafruit BME280 Library @ ^2.3.0
  adafruit/Adafruit OPT3001 Library @ ^1.0.0
  adafruit/Adafruit LTR390 Library @ ^1.0.0
  densaugeo/base64 @ ^1.0.0
build_flags = -w -DNDEBUG -DRADIOLIB_STATIC_ONLY=1 -DRADIOLIB_GODMODE=1
  -D LORA_FREQ=869.618
  -D LORA_BW=62.5
  -D LORA_SF=8
  -D RADIOLIB_EXCLUDE_CC1101=1
  -D RADIOLIB_EXCLUDE_RF69=1
  -D RADIOLIB_EXCLUDE_SX1231=1
  -D RADIOLIB_EXCLUDE_SI443X=1
  -D RADIOLIB_EXCLUDE_RFM2X=1
  -D RADIOLIB_EXCLUDE_SX128X=1
  -D RADIOLIB_EXCLUDE_AFSK=1
  -D RADIOLIB_EXCLUDE_AX25=1
  -D RADIOLIB_EXCLUDE_HELLSCHREIBER=1
  -D RADIOLIB_EXCLUDE_MORSE=1
  -D RADIOLIB_EXCLUDE_APRS=1
  -D RADIOLIB_EXCLUDE_BELL=1
  -D RADIOLIB_EXCLUDE_RTTY=1
  -D RADIOLIB_EXCLUDE_SSTV=1
build_src_filter = +<*.cpp> +<../variant/>

[env:xiao_sensor_beacon]
extends = arduino_base
platform = nordicnrf52
platform_packages =
  framework-arduinoadafruitnrf52 @ https://github.com/meshcore-dev/Adafruit_nRF52_Arduino#d541301
board = seeed-xiao-afruitnrf52-nrf52840
board_build.ldscript = boards/nrf52840_s140_v7.ld
upload_protocol = nrfutil
debug_tool = jlink
lib_deps =
  ${arduino_base.lib_deps}
  https://github.com/oltaco/CustomLFS#0.2.2
build_flags = ${arduino_base.build_flags}
  -I variant
  -D NRF52_PLATFORM
  -D NRF52_POWER_MANAGEMENT
  -D XIAO_NRF52
  -D LFS_NO_ASSERT=1
  -D EXTRAFS=1
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D P_LORA_TX_LED=11
  -D P_LORA_DIO_1=D1
  -D P_LORA_RESET=D2
  -D P_LORA_BUSY=D3
  -D P_LORA_NSS=D4
  -D SX126X_RXEN=D5
  -D SX126X_TXEN=RADIOLIB_NC
  -D SX126X_DIO2_AS_RF_SWITCH=1
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D PIN_WIRE_SCL=D6
  -D PIN_WIRE_SDA=D7
  -D PIN_USER_BTN=PIN_BUTTON1
  -D BEACON_INTERVAL_SECS=300
  -D BEACON_SEND_COUNT=3
